# apiVersion: certmanager.k8s.io/v1alpha1
# kind: Certificate
# metadata:
#   namespace: comical-site-062020-2
#   name: comical-site-tls
# spec:
#   secretName: comical-site-tls
#   dnsNames:
#   - comical.site
#   acme:
#     config:
#     - http01:
#         ingressClass: nginx
#       domains:
#       - comical.site
#   issuerRef:
#     name: letsencrypt-staging
#     kind: ClusterIssuer
