# echo_ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: comical-site
  name: comical-site-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
  - hosts:
    - comical.site
    secretName: letsencrypt-staging
  rules:
  - host: comical.site
    http:
      paths:
      - backend:
          serviceName: comical-site-app
          servicePort: 80
