apiVersion: v1
kind: Service
metadata:
  namespace: comical-site
  name: comical-site-app
spec:
  selector:
    app: comical-site-app
  ports:
  - port: 80
    targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: comical-site
  name: comical-site-app
spec:
  selector:
    matchLabels:
      app: comical-site-app
  replicas: 1
  template:
    metadata:
      labels:
        app: comical-site-app
    spec:
      containers:
      - name: comical-site-app
        image: prequod/inspire-me:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
